spring:
  redis:
    database: 0
    host: 10.0.0.163
    port: 6379
    timeout: 3000
    pool:
      # ????????????????????
      max-active: 8
      # ???????????????????????
      max-wait: -1
      # ???????????
      max-idle: 8
      # ???????????
      min-idle: 0